# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(upload_to=b'productos')),
                ('descripcion', tinymce.models.HTMLField()),
                ('disponible', models.BooleanField(default=False)),
                ('fecha_de_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema_Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('paciente', models.CharField(max_length=100)),
                ('fecha_de_consulta', models.DateTimeField()),
                ('testimonios', models.TextField()),
                ('observaciones', models.TextField()),
                ('habilitado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='author',
        ),
        migrations.DeleteModel(
            name='Publicaciones',
        ),
    ]
