# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_perfil_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='publicaciones',
            name='author',
        ),
        migrations.DeleteModel(
            name='Tema_Publicacion',
        ),
        migrations.DeleteModel(
            name='Perfil_Author',
        ),
        migrations.DeleteModel(
            name='Publicaciones',
        ),
    ]
