# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_testimonios_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_author',
            name='author',
        ),
        migrations.AlterField(
            model_name='publicaciones',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tema_publicacion',
            name='tema',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='imagen',
            field=models.ImageField(default=b'imagenes/biografia.png', upload_to=b'testimonios'),
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Perfil_Author',
        ),
    ]
