# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 01:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0008_auto_20160722_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('Contrasena', models.CharField(max_length=30)),
                ('foto', models.ImageField(default=b'imagenes/usuario.png', upload_to=b'imagenes/usuario')),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('descripcion', models.TextField()),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
